// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: Test.proto

package protoTest

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Test struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bool  bool              `protobuf:"varint,1,opt,name=Bool,proto3" json:"Bool,omitempty"`
	R     int32             `protobuf:"varint,2,opt,name=R,proto3" json:"R,omitempty"`
	I32   int32             `protobuf:"varint,3,opt,name=I32,proto3" json:"I32,omitempty"`
	I64   int64             `protobuf:"varint,4,opt,name=I64,proto3" json:"I64,omitempty"`
	F32   float32           `protobuf:"fixed32,5,opt,name=F32,proto3" json:"F32,omitempty"`
	F64   float64           `protobuf:"fixed64,6,opt,name=F64,proto3" json:"F64,omitempty"`
	S     string            `protobuf:"bytes,7,opt,name=S,proto3" json:"S,omitempty"`
	SBool []bool            `protobuf:"varint,8,rep,packed,name=SBool,proto3" json:"SBool,omitempty"`
	SR    []int32           `protobuf:"varint,9,rep,packed,name=SR,proto3" json:"SR,omitempty"`
	SI32  []int32           `protobuf:"varint,10,rep,packed,name=SI32,proto3" json:"SI32,omitempty"`
	SI64  []int64           `protobuf:"varint,11,rep,packed,name=SI64,proto3" json:"SI64,omitempty"`
	SF32  []float32         `protobuf:"fixed32,12,rep,packed,name=SF32,proto3" json:"SF32,omitempty"`
	SF64  []float64         `protobuf:"fixed64,13,rep,packed,name=SF64,proto3" json:"SF64,omitempty"`
	SS    []string          `protobuf:"bytes,14,rep,name=SS,proto3" json:"SS,omitempty"`
	MS    map[string]string `protobuf:"bytes,15,rep,name=MS,proto3" json:"MS,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Test) Reset() {
	*x = Test{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Test_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Test) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Test) ProtoMessage() {}

func (x *Test) ProtoReflect() protoreflect.Message {
	mi := &file_Test_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Test.ProtoReflect.Descriptor instead.
func (*Test) Descriptor() ([]byte, []int) {
	return file_Test_proto_rawDescGZIP(), []int{0}
}

func (x *Test) GetBool() bool {
	if x != nil {
		return x.Bool
	}
	return false
}

func (x *Test) GetR() int32 {
	if x != nil {
		return x.R
	}
	return 0
}

func (x *Test) GetI32() int32 {
	if x != nil {
		return x.I32
	}
	return 0
}

func (x *Test) GetI64() int64 {
	if x != nil {
		return x.I64
	}
	return 0
}

func (x *Test) GetF32() float32 {
	if x != nil {
		return x.F32
	}
	return 0
}

func (x *Test) GetF64() float64 {
	if x != nil {
		return x.F64
	}
	return 0
}

func (x *Test) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

func (x *Test) GetSBool() []bool {
	if x != nil {
		return x.SBool
	}
	return nil
}

func (x *Test) GetSR() []int32 {
	if x != nil {
		return x.SR
	}
	return nil
}

func (x *Test) GetSI32() []int32 {
	if x != nil {
		return x.SI32
	}
	return nil
}

func (x *Test) GetSI64() []int64 {
	if x != nil {
		return x.SI64
	}
	return nil
}

func (x *Test) GetSF32() []float32 {
	if x != nil {
		return x.SF32
	}
	return nil
}

func (x *Test) GetSF64() []float64 {
	if x != nil {
		return x.SF64
	}
	return nil
}

func (x *Test) GetSS() []string {
	if x != nil {
		return x.SS
	}
	return nil
}

func (x *Test) GetMS() map[string]string {
	if x != nil {
		return x.MS
	}
	return nil
}

var File_Test_proto protoreflect.FileDescriptor

var file_Test_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x54, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x66, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x69, 0x73, 0x6f, 0x6e, 0x22,
	0xec, 0x02, 0x0a, 0x04, 0x54, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x42, 0x6f, 0x6f, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x0c, 0x0a, 0x01,
	0x52, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x52, 0x12, 0x10, 0x0a, 0x03, 0x49, 0x33,
	0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x49, 0x33, 0x32, 0x12, 0x10, 0x0a, 0x03,
	0x49, 0x36, 0x34, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x49, 0x36, 0x34, 0x12, 0x10,
	0x0a, 0x03, 0x46, 0x33, 0x32, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x46, 0x33, 0x32,
	0x12, 0x10, 0x0a, 0x03, 0x46, 0x36, 0x34, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x46,
	0x36, 0x34, 0x12, 0x0c, 0x0a, 0x01, 0x53, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x53,
	0x12, 0x14, 0x0a, 0x05, 0x53, 0x42, 0x6f, 0x6f, 0x6c, 0x18, 0x08, 0x20, 0x03, 0x28, 0x08, 0x52,
	0x05, 0x53, 0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x53, 0x52, 0x18, 0x09, 0x20, 0x03,
	0x28, 0x05, 0x52, 0x02, 0x53, 0x52, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x49, 0x33, 0x32, 0x18, 0x0a,
	0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x53, 0x49, 0x33, 0x32, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x49,
	0x36, 0x34, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x03, 0x52, 0x04, 0x53, 0x49, 0x36, 0x34, 0x12, 0x12,
	0x0a, 0x04, 0x53, 0x46, 0x33, 0x32, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x02, 0x52, 0x04, 0x53, 0x46,
	0x33, 0x32, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x46, 0x36, 0x34, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x01,
	0x52, 0x04, 0x53, 0x46, 0x36, 0x34, 0x12, 0x0e, 0x0a, 0x02, 0x53, 0x53, 0x18, 0x0e, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x02, 0x53, 0x53, 0x12, 0x2f, 0x0a, 0x02, 0x4d, 0x53, 0x18, 0x0f, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x5f, 0x63, 0x6f, 0x6d, 0x70,
	0x61, 0x72, 0x69, 0x73, 0x6f, 0x6e, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x2e, 0x4d, 0x53, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x02, 0x4d, 0x53, 0x1a, 0x35, 0x0a, 0x07, 0x4d, 0x53, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x0c,
	0x5a, 0x0a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x54, 0x65, 0x73, 0x74, 0x2f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Test_proto_rawDescOnce sync.Once
	file_Test_proto_rawDescData = file_Test_proto_rawDesc
)

func file_Test_proto_rawDescGZIP() []byte {
	file_Test_proto_rawDescOnce.Do(func() {
		file_Test_proto_rawDescData = protoimpl.X.CompressGZIP(file_Test_proto_rawDescData)
	})
	return file_Test_proto_rawDescData
}

var file_Test_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Test_proto_goTypes = []interface{}{
	(*Test)(nil), // 0: format_comparison.Test
	nil,          // 1: format_comparison.Test.MSEntry
}
var file_Test_proto_depIdxs = []int32{
	1, // 0: format_comparison.Test.MS:type_name -> format_comparison.Test.MSEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_Test_proto_init() }
func file_Test_proto_init() {
	if File_Test_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Test_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Test); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Test_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Test_proto_goTypes,
		DependencyIndexes: file_Test_proto_depIdxs,
		MessageInfos:      file_Test_proto_msgTypes,
	}.Build()
	File_Test_proto = out.File
	file_Test_proto_rawDesc = nil
	file_Test_proto_goTypes = nil
	file_Test_proto_depIdxs = nil
}
